# -*- mode: ruby -*-
# vi: set ft=ruby :
mydomain="puppetspecialist.nl"

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-6.7"
  config.vm.hostname = "rh6.#{mydomain}"

  config.vm.provision "shell", inline: <<-SHELL
    echo 10.20.0.10 master.#{mydomain} master >> /etc/hosts
    rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-6.noarch.rpm
    yum -y install puppet-agent
    cp /vagrant/puppet/puppet.conf /etc/puppetlabs/puppet/puppet.conf
    mkdir -p /etc/puppetlabs/puppet/ssl/{public,private}_keys/
    cp /vagrant/puppet/keys/public_keys/rh6.#{mydomain}.pem /etc/puppetlabs/puppet/ssl/public_keys/
    cp /vagrant/puppet/keys/private_keys/rh6.#{mydomain}.pem /etc/puppetlabs/puppet/ssl/private_keys/
    /opt/puppetlabs/bin/puppet agent -t
  SHELL

end
